#!/bin/bash

IFS="$(printf '\n\t')"
cd "$(dirname "$0")"

SCRIPT_NAME="$(basename "$0")"

echo -n 'New project name: '
read new_project_name

confirm_new_project_name='?'
while [[ "${confirm_new_project_name}" != 'y' && "${confirm_new_project_name}" != 'n' ]] ; do
    echo -en "\nAre you sure you want to name your project '${new_project_name}'? [y/n] "
    read confirm_new_project_name
done

if [[ "${confirm_new_project_name}" == 'n' ]] ; then
    echo -e "Exiting.\n"
    exit 1
fi

# Rename all instances of `mydjangoproject` in the repo to $new_project_name,
# excluding the .git/ directory (or Bad Things will happen).
#
# Note: Without LANG=C, sed assumes that files are encoded in whatever encoding
# is specified in $LANG, aka 'en_CA.UTF-8'. The C encoding treats all ASCII
# characters as themselves and non-ASCII characters as literals.
# See http://stackoverflow.com/questions/11287564/
LANG=C find . -type f ! -name "${SCRIPT_NAME}"  -not -path "./.git*" -exec sed -i '' "s/mydjangoproject/${new_project_name}/" {} \;

# Rename the config root directory
mv mydjangoproject/ "${new_project_name}"

echo 'Making manage.py executable.'
chmod +x manage.py

echo 'Appending .postactivate to .gitignore.'
echo '.postactivate' >> .gitignore

echo 'Done.'
echo -e "\nYou can delete this file now.\n\n"
